/**
 * LOCAL BRAND LOGO MAPPING
 * 
 * This file maps brand names to their local PNG file paths.
 * Logos are stored in public/assets/brand-logos/
 * 
 * Generated by: server/scripts/download-brand-logos.js
 */

const BRAND_LOGO_MAPPING = {
  acer:        '/assets/brand-logos/acer.png',
  apple:       '/assets/brand-logos/apple.png',
  asus:        '/assets/brand-logos/asus.png',
  blackberry:  '/assets/brand-logos/blackberry.png',
  dell:        '/assets/brand-logos/dell.png',
  google:      '/assets/brand-logos/google.png',
  'hmd global': '/assets/brand-logos/hmd-global.png',
  nokia:       '/assets/brand-logos/nokia.png',
  htc:         '/assets/brand-logos/htc.png',
  huawei:      '/assets/brand-logos/huawei.png',
  lg:          '/assets/brand-logos/lg.png',
  lenovo:      '/assets/brand-logos/lenovo.png',
  microsoft:   '/assets/brand-logos/microsoft.png',
  windows:     '/assets/brand-logos/microsoft.png',
  motorola:    '/assets/brand-logos/motorola.png',
  oneplus:     '/assets/brand-logos/oneplus.png',
  samsung:     '/assets/brand-logos/samsung.png',
  sony:        '/assets/brand-logos/sony.png',
  toshiba:     '/assets/brand-logos/toshiba.png',
  xiaomi:      '/assets/brand-logos/xiaomi.png'
};

/**
 * Get the local logo path for a given brand name
 * @param {string} name - Brand name
 * @returns {string|null} - Local path to logo file
 */
function getBrandLogoPath(name) {
  if (!name) return null;
  const normalized = String(name).trim().toLowerCase();

  if (BRAND_LOGO_MAPPING[normalized]) {
    return BRAND_LOGO_MAPPING[normalized];
  }

  // Try comma-separated compound names (first match wins).
  if (normalized.includes(',')) {
    for (const part of normalized.split(',').map((s) => s.trim())) {
      if (BRAND_LOGO_MAPPING[part]) return BRAND_LOGO_MAPPING[part];
    }
  }

  return null;
}

module.exports = {
  BRAND_LOGO_MAPPING,
  getBrandLogoPath
};
